[package]
name = "kista"
version = "0.1.0"
authors = ["Richard Newman <rnewman@twinql.com>"]

[dependencies]
arrayref = "0.3"
bincode = "0.9"
failure = "0.1"
lmdb = "0.7"
ordered-float = "0.5"
uuid = "0.5"

serde = "1.0"

[dev-dependencies]
tempdir = "0.3"